### ISSUE TITLE
itzkiba.grandpa_demon

### ISSUE THREAD

**Issue by Austinkeith2010** [user95401/Geode-Mod-Comments#100]

**Comment by Austinkeith2010** [comment]
grandma demon mod when?

**Comment by Foxiseminger** [comment]
@Austinkeith2010 why 😭

**Comment by Jacer245** [comment]
Grandpa Demon detected, loser! Grandpa Demon is illegitimate and will not be allowed for use in LevelInfoLayer. Please disable the mod in order to continue searching.

**Comment by Austinkeith2010** [comment]
shut it
