### ISSUE TITLE
I keep getting "Body cannot be blank" and I cannot comment

### ISSUE THREAD

**Issue by REALCraylenGD** [user95401/Geode-Mod-Comments#364]
I press "Send New" and this pops up
![image](https://github.com/user-attachments/assets/6842b89b-efb2-4f6e-9014-813254c7a833)
please help lol
yes i have authenticated
idk what happened

**Comment by REALCraylenGD** [comment]
this has still happened with the new update

**Comment by user95401** [comment]
![image](https://github.com/user-attachments/assets/42547786-4ae2-482e-8775-42d56bb264ef)

**Comment by REALCraylenGD** [comment]
it happens before I can even attempt to write anything

**Comment by user95401** [comment]
video pls

**Comment by REALCraylenGD** [comment]
nevermind I just didn't know how to type something in

**Comment by REALCraylenGD** [comment]
i'm dumb sometimes
